config/routes.rb
Rails.application.routes.draw do

  resources :notes

  root 'notes#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def edit
    @note = Note.find(params[:id])
  end

  def create
    @note = Note.new(params.require(:note).permit(:title, :category, :content, :author))
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(params.require(:note).permit(:title, :category, :content, :author))
       redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    redirect_to notes_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: @note, local: true) do |form| %>

  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@note.errors.count, "error") %> prohibited
        this note from being saved:
      </h2>
      <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card stickynoteShow stickynoteForm">
    <form>
      <%= form.label :author, class: "control-label" %>
      <div class="col-md-12">
        <%= form.text_field :author, class: "control-form" %>
      </div>

      <%= form.label :title, class: "control-label" %>
      <div class="col-md-12">
        <%= form.text_field :author, class: "control-form" %>
      </div>

      <%= form.label :category, class: "control-label" %>
      <div class="col-md-12">
        <%= form.text_field :author, class: "control-form" %>
      </div>

      <%= form.label :content, class: "control-label" %>

      <div class="col-md-12">
        <%= form.text_area :content, class: "control-form" %>
      </div>

      <%= form.submit "Save", class: "btn btn-success" %>
    </form>
  </div>
<% end %>

app/views/notes/_header.html.erb
<div class="header">
  <h1>Simple Notes</h1>
  <%= link_to 'Notes', notes_path %> -
  <%= link_to 'New Note', new_note_path %> -
  About
</div>

app/views/notes/edit.html.erb
<%= render 'form' %>

app/views/notes/index.html.erb
<div class="noteCollection">
  <% @notes.each do |note| %>
    <div class="card stickynote">
      <div class="card-body">
        <%= link_to note_path(note) do %>
          <h5 class="card-title">#<%= note.category %> - <%= note.title %></h5>
        <% end %>
        <h6 class="card-subtitle mb-2 text-muted">Author: <%= note.author %></h6>
        <p class="card-text"> <%= note.content.truncate(100) %></p>
        <%= link_to 'Edit', edit_note_path(note), class: "card-link" %>
        <%= link_to 'Destroy', note_path(note), method: :delete, data: { confirm: 'Are you sure?'}, class: "card-link" %>
      </div>
    </div>
  <% end %>
</div>

app/views/notes/new.html.erb
<%= render 'form' %>

app/views/notes/show.html.erb
<div class="card stickynoteShow">
  <div class="card-body">
    <h5 class="card-title">#<%= @note.category %> - <%= @note.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Author: <%= @note.author %></h6>
    <p class="card-text"> <%= @note.content %></p>
    <%= link_to 'Edit', edit_note_path(@note), class: "card-link" %>
    <%= link_to 'Destroy', note_path(@note), method: :delete, data: { confirm: 'Are you sure?'}, class: "card-link" %>
  </div>
</div>